import { Helmet } from 'react-helmet-async';

interface SEOProps {
  title: string;
  description: string;
  keywords?: string;
  canonical: string;
  /** Explicit OG image URL. If omitted, a branded card is generated by /api/og. */
  ogImage?: string;
  /** Overrides the OG card heading. Defaults to `title`. Use this when the full
   *  document <title> is long ("Direct Hire in Brazil — Kaptas Global | One-Time
   *  18% Fee, No Retainer") and you want a shorter, punchier card heading. */
  ogTitle?: string;
  /** Overrides the OG card subtitle. Defaults to `description`. */
  ogSubtitle?: string;
  /** Small all-caps label above the OG card title. Examples: "DIRECT HIRE",
   *  "BLOG", "PRICING". Skipped on the home page so the logo carries the brand. */
  eyebrow?: string;
  /** og:type — defaults to "website". Use "article" for blog posts. */
  ogType?: "website" | "article" | "profile" | "book";
  schemas?: object[];
}

// During the WordPress → Vercel migration both kaptasglobal.io (live WP)
// and kaptas-global.vercel.app (this build) serve the same content. To
// avoid duplicate-content penalties and to keep the canonical signal on
// the real domain, every *.vercel.app hostname is served as noindex. The
// X-Robots-Tag header in vercel.json covers crawlers that do not run JS;
// this runtime check covers JS-rendering crawlers as a second layer.
function isStagingHost(): boolean {
  if (typeof window === "undefined") return false;
  return window.location.hostname.endsWith(".vercel.app");
}

// Dynamic-OG endpoint. The Edge Function at /api/og renders 1200x630 branded
// cards with the site's own colors, logo, and Inter type. By always pointing
// at the production hostname, the URL embedded in a prerendered preview is
// the same URL social crawlers will hit from anywhere — no environment switch
// needed.
const OG_IMAGE_BASE = "https://kaptasglobal.io/api/og";

function buildOgImageUrl(opts: {
  title: string;
  subtitle?: string;
  eyebrow?: string;
}): string {
  const params = new URLSearchParams();
  params.set("title", opts.title);
  if (opts.subtitle) params.set("subtitle", opts.subtitle);
  if (opts.eyebrow) params.set("eyebrow", opts.eyebrow);
  return `${OG_IMAGE_BASE}?${params.toString()}`;
}

export function SEO({
  title,
  description,
  keywords,
  canonical,
  ogImage,
  ogTitle,
  ogSubtitle,
  eyebrow,
  ogType = "website",
  schemas = [],
}: SEOProps) {
  const image =
    ogImage ??
    buildOgImageUrl({
      title: ogTitle ?? title,
      subtitle: ogSubtitle ?? description,
      eyebrow,
    });
  const robots = isStagingHost() ? "noindex, follow" : "index, follow";
  return (
    <Helmet>
      <title>{title}</title>
      <meta name="description" content={description} />
      {keywords && <meta name="keywords" content={keywords} />}
      <meta name="robots" content={robots} />
      <link rel="canonical" href={canonical} />

      {/* Open Graph */}
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:type" content={ogType} />
      <meta property="og:url" content={canonical} />
      <meta property="og:image" content={image} />
      <meta property="og:image:type" content="image/png" />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta property="og:site_name" content="Kaptas Global" />
      <meta property="og:locale" content="en_US" />

      {/* Twitter Card */}
      {/* twitter:site omitted intentionally — Kaptas does not maintain an X/Twitter account.
          When/if an account is created, add: <meta name="twitter:site" content="@handle" /> */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={image} />

      {/* JSON-LD Schemas */}
      {schemas.map((schema, i) => (
        <script key={i} type="application/ld+json">
          {JSON.stringify(schema)}
        </script>
      ))}
    </Helmet>
  );
}
